language: node_js
node_js:
      - "node"
script: ./node_modules/.bin/karma start browser-test/karma.config.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install
addons:
    chrome: stable
